[package]
name = "ups_monitor_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.2"
ina219_rs = "0.2.1"


ctrlc = "3.2.3"
tracing = "0.1.36"